export const ENV = {
  MPESA_CONSUMER_KEY: "yhAQOrn9eNRJsBJ8NDsQz0I4Nu2XxDZ182e2YYMDFY7PVobo",
  MPESA_CONSUMER_SECRET: "HKqljggp7UzwhZxm1op4XqJEFAVhYGHqjUgBiCmsrFiI15oR1JmUUauppGi1cXY5",
  MPESA_SHORTCODE: "174379", // default sandbox shortcode, replace if different
  MPESA_PASSKEY: "PLACEHOLDER_PASSKEY", // replace with sandbox passkey if provided
  CALLBACK_URL: "https://REPLACE_WITH_YOUR_CALLBACK_URL/callback",

  FIREBASE_PROJECT_ID: "ridercms-ced94",
  FIREBASE_CLIENT_EMAIL: "PLACEHOLDER_FIREBASE_CLIENT_EMAIL",
  FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nPLACEHOLDER_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
};
